helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-query-router
    forcestring: true
  - name: image.tag
    value: main@sha256:1beb724fd664b98cfc33d5b2354d228b2bc3e36560250c34e3f0fd06846fc4b2
    forcestring: true
