helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-query-router
    forcestring: true
  - name: image.tag
    value: main@sha256:77748ad3eaad7e40db5828fac8ac8a2a9c5e0510352f04f58ed7f286ea28654b
    forcestring: true
